import React from "react";
import { GiCompass, GiDiamondHard, GiStabbedNote } from "react-icons/gi";
import ts1 from "../assets/11.png";
import ts2 from "../assets/12.png";
import ts3 from "../assets/13.png";
import ts4 from "../assets/14.png";
import ts5 from "../assets/15.png";
import ts6 from "../assets/16.png";
import ts7 from "../assets/17.png";
import ts8 from "../assets/18.png";
import ts9 from "../assets/19.png";
import ts10 from "../assets/20.png";
import t1 from "../assets/1.png";
import t2 from "../assets/2.png";
import t3 from "../assets/3.png";
import t4 from "../assets/4.png";
import t5 from "../assets/5.png";
import t6 from "../assets/6.png";
import t7 from "../assets/7.png";
import t8 from "../assets/8.png";
import t9 from "../assets/9.png";
import t10 from "../assets/10.png";

import casualshirt1 from "../tempDataSet/casual-shirts-001.jpg";
import casualshirt2 from "../tempDataSet/casual-shirts-002.jpg";
import casualshirt3 from "../tempDataSet/casual-shirts-003.jpg";

import denim1 from "../tempDataSet/denim-001.jpg";
import denim2 from "../tempDataSet/denim-002.jpg";
import denim3 from "../tempDataSet/denim-003.jpg";
import denim4 from "../tempDataSet/denim-004.jpg";
import denim5 from "../tempDataSet/denim-005.jpg";
import denim6 from "../tempDataSet/denim-006.jpg";

import dress1 from "../tempDataSet/dress-001.jpg";
import dress2 from "../tempDataSet/dress-002.jpg";
import dress3 from "../tempDataSet/dress-003.jpg";

import formalshirt1 from "../tempDataSet/formal-shirt-001.jpg";
import formalshirt2 from "../tempDataSet/formal-shirt-002.jpg";
import formalshirt3 from "../tempDataSet/formal-shirt-003.jpg";

import short1 from "../tempDataSet/shorts-001.jpg";
import short2 from "../tempDataSet/shorts-002.jpg";
import short3 from "../tempDataSet/shorts-003.jpg";
import short4 from "../tempDataSet/shorts-004.jpg";
import short5 from "../tempDataSet/shorts-005.jpeg";
import short6 from "../tempDataSet/shorts-006.jpeg";

import skirt1 from "../tempDataSet/skirt-001.jpg";
import skirt2 from "../tempDataSet/skirt-002.jpg";
import skirt3 from "../tempDataSet/skirt-003.jpg";

import top1 from "../tempDataSet/tops-001.jpg";
import top2 from "../tempDataSet/tops-002.jpeg";
import top3 from "../tempDataSet/tops-003.jpg";

import tshirt1 from "../tempDataSet/t-shirt-001.jpg";
import tshirt2 from "../tempDataSet/t-shirt-002.jpg";
import tshirt3 from "../tempDataSet/t-shirt-003.jpg";

import toy1 from "../tempDataSet/toys-001.jpg";
import toy2 from "../tempDataSet/toys-002.png";
import toy3 from "../tempDataSet/toys-003.jpg";
import toy4 from "../tempDataSet/toys-004.jpg";
import toy5 from "../tempDataSet/toys-005.jpg";
import toy6 from "../tempDataSet/toys-006.jpg";
import toy7 from "../tempDataSet/toys-007.jpg";
import toy8 from "../tempDataSet/toys-008.jpg";
import toy9 from "../tempDataSet/toys-009.jpg";
import toy10 from "../tempDataSet/toys-010.jpg";
import toy11 from "../tempDataSet/toys-011.jpg";
import toy12 from "../tempDataSet/toys-012.jpg";
import toy13 from "../tempDataSet/toys-013.jpg";
import toy14 from "../tempDataSet/toys-014.jpg";
import toy15 from "../tempDataSet/toys-015.jpg";

export const links = [
  {
    id: 1,
    text: "home",
    url: "/",
  },
  {
    id: 2,
    text: "about",
    url: "/about",
  },
  {
    id: 3,
    text: "products",
    url: "/products",
  },
];

export const services = [
  {
    id: 1,
    icon: <GiCompass />,
    title: "mission",
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptates, ea. Perferendis corrupti reiciendis nesciunt rerum velit autem unde numquam nisi",
  },
  {
    id: 2,
    icon: <GiDiamondHard />,
    title: "vision",
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptates, ea. Perferendis corrupti reiciendis nesciunt rerum velit autem unde numquam nisi",
  },
  {
    id: 3,
    icon: <GiStabbedNote />,
    title: "history",
    text: "Lorem ipsum, dolor sit amet consectetur adipisicing elit. Voluptates, ea. Perferendis corrupti reiciendis nesciunt rerum velit autem unde numquam nisi",
  },
];

export const data = [
  {
    id: 1,
    name: "Cotton Jogger",
    price: 99999,
    image: `${t1}`,
    colors: ["#ff0000", "#808080", "#ff00ff"],
    company: "Dilly & Carlo",
    description: "More Men from Dilly & Carlo",
    category: "trouser",
    shipping: true,
    gen: "male",
    stock: 52,
    reviews: 25,
    stars: 4.2,
    featured: true,
  },
  {
    id: 2,
    name: "Casual Shirt-1",
    price: 200000,
    image: `${casualshirt1}`,
    colors: ["#ff0000"],
    company: "Moose",
    description: "Cozy Plaid for Weekend Relaxation.",
    category: "casual-shirt",
    shipping: true,
    gen: "male",
    stock: 18,
    reviews: 25,
    stars: 3.5,
    featured: true,
  },
  {
    id: 3,
    name: "casualShirt002",
    price: 180000,
    image: `${casualshirt2}`,
    colors: ["#ff0000"],
    company: "Moose",
    description: "Sleek Modernity for Sharp Dressing",
    category: "casual-shirt",
    shipping: true,
    gen: "male",
    stock: 23,
    reviews: 24,
    stars: 4.5,
    featured: true,
  },
  {
    id: 4,
    name: "Polo T-shirt",
    price: 129999,
    image: `${ts1}`,
    colors: ["#ff0000"],
    company: "T-shirt Republic",
    description: "More Men from T-shirt Republic",
    category: "T-shirt",
    shipping: false,
    gen: "male",
    stock: 55,
    reviews: 25,
    stars: 4.5,
    featured: true,
  },
  {
    id: 5,
    name: "Cotton Jogger",
    price: 100000,
    image: `${t2}`,
    colors: ["#ff0000", "#ff00ff"],
    company: "Loomze",
    description: "More Men from Loomze",
    category: "trouser",
    shipping: true,
    gen: "male",
    stock: 785,
    reviews: 28,
    stars: 3.5,
    featured: true,
  },
  {
    id: 6,
    name: "casualShirt003",
    price: 150000,
    image: `${casualshirt3}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "polo",
    description: "Timeless Chambray, Casual Elegance Always.",
    category: "casual-shirt",
    shipping: true,
    gen: "male",
    stock: 15,
    reviews: 38,
    stars: 4.5,
    featured: false,
  },
  {
    id: 7,
    name: "Classic Jeans",
    price: 250000,
    image: `${denim1}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "polo",
    description: "Classic Jeans, Timeless Style Essential.",
    category: "denim",
    shipping: true,
    gen: "male",
    stock: 50,
    reviews: 215,
    stars: 4.5,
  },
  {
    id: 8,
    name: "Comfort T-shirt",
    price: 89000,
    image: `${ts2}`,
    colors: ["#ff00ff", "#0000ff"],
    company: "Moose",
    description: "More Men from Moose",
    category: "T-shirt",
    shipping: true,
    gen: "male",
    stock: 15,
    reviews: 5,
    stars: 3.2,
  },
  {
    id: 9,
    name: "Men's Slim-Fit",
    price: 110000,
    image: `${t3}`,
    colors: ["#ff00ff", "#00ff00", "#ffff00", "#0000ff"],
    company: "Moose",
    description: "More Men from Moose",
    category: "trouser",
    shipping: false,
    gen: "male",
    stock: 15,
    reviews: 78,
    stars: 4.5,
  },
  {
    id: 10,
    name: "Slim Fit",
    price: 145000,
    image: `${denim2}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Moose",
    description: "Slim Fit, Modern and Versatile.",
    category: "denim",
    shipping: true,
    gen: "male",
    stock: 500,
    reviews: 250,
    stars: 4.5,
  },
  {
    id: 11,
    name: "Weekend Wear",
    price: 250000,
    image: `${denim3}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Moose",
    description: "Relaxed Comfort, Casual Weekend Wear",
    category: "denim",
    shipping: false,
    gen: "male",
    stock: 500,
    reviews: 485,
    stars: 5.0,
  },
  {
    id: 12,
    name: "Crew T-shirt",
    price: 99999,
    image: `${ts3}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Moose",
    description: "More Men from Moose",
    category: "T-shirt",
    shipping: true,
    gen: "male",
    stock: 80,
    reviews: 52,
    stars: 4.5,
  },
  {
    id: 13,
    name: "Men's Slim-Fit",
    price: 112000,
    image: `${t4}`,
    colors: ["#ff0000", "#0000ff", "#ff00ff"],
    company: "Dilly & Carlo",
    description: "More Men from Dilly & Carlo",
    category: "trouser",
    shipping: true,
    gen: "male",
    stock: 120,
    reviews: 89,
    stars: 4.8,
  },
  {
    id: 14,
    name: "waist denim",
    price: 250000,
    image: `${denim4}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Brandability",
    description: "Ladies High waist denim",
    category: "denim",
    shipping: true,
    gen: "female",
    stock: 120,
    reviews: 250,
    stars: 4.5,
  },
  {
    id: 15,
    name: "Fit denim",
    price: 105000,
    image: `${denim5}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Brandability",
    description: "Ladies Skinny Fit denim",
    category: "denim",
    shipping: true,
    gen: "female",
    stock: 500,
    reviews: 250,
    stars: 4.5,
  },
  {
    id: 16,
    name: "Fit T-shirt",
    price: 99999,
    image: `${ts4}`,
    colors: ["#ffff00", "#808080", "#0000ff"],
    company: "T-shirt Republic",
    description: "More Men from T-shirt Republic",
    category: "T-shirt",
    shipping: true,
    gen: "male",
    stock: 120,
    reviews: 25,
    stars: 4.5,
  },
  {
    id: 17,
    name: "Stretch Chino Pant",
    price: 113099,
    image: `${t5}`,
    colors: ["#0000ff", "#808080", "#ff00ff"],
    company: "Loomze",
    description: "More Men from Loomze",
    category: "trouser",
    shipping: false,
    gen: "male",
    stock: 120,
    reviews: 2,
    stars: 1.2,
  },
  {
    id: 18,
    name: "Denim Jeans",
    price: 250000,
    image: `${denim6}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Moose",
    description: "Ladies Fashion Denim Jeans",
    category: "denim",
    shipping: true,
    gen: "female",
    stock: 78,
    reviews: 15,
    stars: 3.5,
  },
  {
    id: 19,
    name: "Girls dress",
    price: 150000,
    image: `${dress1}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Sheetal",
    description: "Girls dress",
    category: "dress",
    shipping: true,
    gen: "female",
    stock: 150,
    reviews: 260,
    stars: 3.5,
  },
  {
    id: 20,
    name: "Cotton T-shirt",
    price: 110000,
    image: `${ts5}`,
    colors: ["#ff0000", "#00ff00", "#ffff00"],
    company: "Nike",
    description: "More Men from Nike",
    category: "T-shirt",
    shipping: true,
    gen: "male",
    stock: 15,
    reviews: 26,
    stars: 3.5,
  },
  {
    id: 21,
    name: "Chino Pant",
    price: 140000,
    image: `${t6}`,
    colors: ["#0000ff", "#808080", "#ff00ff"],
    company: "Moose",
    description: "More Men from Moose",
    category: "trouser",
    shipping: false,
    gen: "male",
    stock: 15,
    reviews: 26,
    stars: 3.5,
  },
  {
    id: 22,
    name: "Casual Dress",
    price: 450000,
    image: `${dress2}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Sheetal",
    description: "Casual Dress",
    category: "dress",
    shipping: true,
    gen: "female",
    stock: 80,
    reviews: 45,
    stars: 4.0,
  },
  {
    id: 23,
    name: "Asymmetric Dress",
    price: 230000,
    image: `${dress3}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Sheetal",
    description: "Asymmetric Dress",
    category: "dress",
    shipping: true,
    gen: "female",
    stock: 150,
    reviews: 50,
    stars: 2.5,
  },
  {
    id: 24,
    name: "Polo T-shirt",
    price: 119999,
    image: `${ts6}`,
    colors: ["#0000ff", "#ff00ff"],
    company: "Nike",
    description: "More Men from Nike",
    category: "T-shirt",
    shipping: true,
    gen: "male",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 25,
    name: "Cotton Casual Pant",
    price: 249999,
    image: `${t7}`,
    colors: ["#ff0000", "#808080", "#0000ff"],
    company: "Dilly & Carlo",
    description: "More Men from Dilly & Carlo",
    category: "trouser",
    shipping: true,
    gen: "male",
    stock: 18,
    reviews: 2,
    stars: 4.5,
  },
  {
    id: 26,
    name: "formal Shirt-1",
    price: 280000,
    image: `${formalshirt1}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "polo",
    description: "Classic Elegance, Perfect for Business.",
    category: "formal-shirt",
    shipping: true,
    gen: "male",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 27,
    name: "formal Shirt-2",
    price: 190000,
    image: `${formalshirt2}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "polo",
    description: "Timeless Patterns, Elevating Your Wardrobe",
    category: "formal-shirt",
    shipping: true,
    gen: "male",
    stock: 89,
    reviews: 75,
    stars: 3.5,
  },
  {
    id: 28,
    name: "Comfort T-shirt",
    price: 210000,
    image: `${ts7}`,
    colors: ["#ff0000", "#ffff00", "#0000ff"],
    company: "Everlane",
    description: "More Men from Everlane",
    category: "T-shirt",
    shipping: true,
    gen: "male",
    stock: 170,
    reviews: 50,
    stars: 4.5,
  },
  {
    id: 29,
    name: "slim fit straight",
    price: 159999,
    image: `${t8}`,
    colors: ["#00ff00"],
    company: "Loomze",
    description: "More Men from Loomze",
    category: "trouser",
    shipping: true,
    gen: "male",
    stock: 17,
    reviews: 5,
    stars: 4.0,
  },
  {
    id: 30,
    name: "formal Shirt-3",
    price: 150000,
    image: `${formalshirt3}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "polo",
    description: "Sharp Lines, Exuding Sophistication.",
    category: "formal-shirt",
    shipping: true,
    gen: "male",
    stock: 170,
    reviews: 50,
    stars: 3.5,
  },
  {
    id: 31,
    name: "cool short",
    price: 80000,
    image: `${short1}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "company A",
    description: "Cool and Casual Everyday Shorts.",
    category: "shorts",
    shipping: true,
    gen: "male",
    stock: 65,
    reviews: 45,
    stars: 4.0,
  },
  {
    id: 32,
    name: "Crew T-shirt",
    price: 119999,
    image: `${ts8}`,
    colors: ["#ffff00", "#808080", "#ff00ff"],
    company: "Everlane",
    description: "More Men from Everlane",
    category: "T-shirt",
    shipping: true,
    gen: "male",
    stock: 170,
    reviews: 58,
    stars: 4.0,
  },
  {
    id: 33,
    name: "Fit Formal Trouser",
    price: 210099,
    image: `${t9}`,
    colors: ["#ff0000", "#00ff00", "#0000ff", "#ffff00", "#808080", "#ff00ff"],
    company: "Moose",
    description: "More Men from Moose",
    category: "trouser",
    shipping: true,
    gen: "male",
    stock: 17,
    reviews: 5,
    stars: 3.8,
  },
  {
    id: 34,
    name: "summer short",
    price: 205000,
    image: `${short2}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "company A",
    description: "Stylish Comfort for Summer Fashion.",
    category: "shorts",
    shipping: true,
    gen: "male",
    stock: 47,
    reviews: 35,
    stars: 3.5,
  },
  {
    id: 35,
    name: "fit short",
    price: 90000,
    image: `${short3}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "company C",
    description: "Relaxed Fit, Perfect for Relaxation.",
    category: "shorts",
    shipping: true,
    gen: "male",
    stock: 180,
    reviews: 98,
    stars: 4.5,
  },
  {
    id: 36,
    name: "Fit T-shirt",
    price: 119999,
    image: `${ts9}`,
    colors: ["#808080", "#ff00ff", "#ffff00"],
    company: "Hugo Boss",
    description: "More Men from Hugo Boss",
    category: "T-shirt",
    shipping: true,
    gen: "male",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 37,
    name: "casual trousers",
    price: 320000,
    image: `${t10}`,
    colors: ["#808080"],
    company: "Dilly & Carlo",
    description: "More Men from Dilly & Carlo",
    category: "trouser",
    shipping: true,
    gen: "male",
    stock: 170,
    reviews: 500,
    stars: 5,
  },
  {
    id: 38,
    name: "Girls denim short",
    price: 180000,
    image: `${short4}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Roxy",
    description: "Girls denim short",
    category: "shorts",
    shipping: true,
    gen: "female",
    stock: 7,
    reviews: 45,
    stars: 3.2,
  },
  {
    id: 39,
    name: "Loose Fit Shorts",
    price: 450000,
    image: `${short5}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Roxy",
    description: "Loose Fit Shorts",
    category: "shorts",
    shipping: true,
    gen: "female",
    stock: 80,
    reviews: 50,
    stars: 4.5,
  },
  {
    id: 40,
    name: "Cotton T-shirt",
    price: 180000,
    image: `${ts10}`,
    colors: ["#ff0000", "#0000ff"],
    company: "Hugo Boss",
    description: "More Men from Hugo Boss",
    category: "T-shirt",
    shipping: true,
    gen: "male",
    stock: 170,
    reviews: 32,
    stars: 3.0,
  },
  {
    id: 41,
    name: "run shorts",
    price: 100000,
    image: `${short6}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Moose",
    description: "run shorts",
    category: "shorts",
    shipping: true,
    gen: "female",
    stock: 0,
    reviews: 5,
    stars: 3.0,
  },
  {
    id: 42,
    name: "Girl Skirt",
    price: 150000,
    image: `${skirt1}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Moose",
    description: "Richirobins",
    category: "skirt",
    shipping: true,
    gen: "female",
    stock: 69,
    reviews: 4,
    stars: 4.0,
  },
  {
    id: 43,
    name: "skirts002",
    price: 340000,
    image: `${skirt2}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Moose",
    description: "Topshop",
    category: "skirt",
    shipping: true,
    gen: "female",
    stock: 170,
    reviews: 50,
    stars: 5.0,
  },
  {
    id: 44,
    name: "Girls skirt",
    price: 450000,
    image: `${skirt3}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Moose",
    description: "Prada",
    category: "skirt",
    shipping: true,
    gen: "female",
    stock: 22,
    reviews: 7,
    stars: 2.5,
  },
  {
    id: 45,
    name: "Summer cotton top",
    price: 210000,
    image: `${top1}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Moose",
    description: "Classic Elegance, Perfect for Business.",
    category: "top",
    shipping: true,
    gen: "female",
    stock: 20,
    reviews: 4,
    stars: 4.0,
  },
  {
    id: 46,
    name: "Short top",
    price: 220000,
    image: `${top2}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Moose",
    description: "Cozy Plaid for Weekend Relaxation",
    category: "top",
    shipping: true,
    gen: "female",
    stock: 45,
    reviews: 15,
    stars: 3.5,
  },
  {
    id: 47,
    name: "Ladies' top",
    price: 180000,
    image: `${top3}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Nike",
    description: "Unique Prints for Personalized Style.",
    category: "top",
    shipping: true,
    gen: "female",
    stock: 100,
    reviews: 47,
    stars: 4.8,
  },
  {
    id: 48,
    name: "Sleeve T-Shirts",
    price: 180000,
    image: `${tshirt1}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Zara",
    description: "Summer/Cotton/Short Sleeve T-Shirts",
    category: "t-shirt",
    shipping: true,
    gen: "female",
    stock: 7,
    reviews: 8,
    stars: 2.8,
  },
  {
    id: 49,
    name: "Ladies T-shirt",
    price: 220000,
    image: `${tshirt2}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Moose",
    description: "Ladies T-shirt",
    category: "t-shirt",
    shipping: true,
    gen: "female",
    stock: 180,
    reviews: 90,
    stars: 4.0,
  },
  {
    id: 50,
    name: "neck t-shirt",
    price: 380000,
    image: `${tshirt3}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Zara",
    description: "Casual crew neck t-shirt",
    category: "t-shirt",
    shipping: true,
    gen: "female",
    stock: 80,
    reviews: 95,
    stars: 4.5,
  },
  {
    id: 51,
    name: "building block-1",
    price: 400000,
    image: `${toy1}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Crispy toys",
    description:
      "Mega Blocks First Builders Big Building Blocks Toys Bag 80pcs Toddlers Kids",
    category: "building-blocks",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 52,
    name: "building block-2",
    price: 380000,
    image: `${toy2}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Gadget City",
    description: "Kids Building Blocks",
    category: "building-blocks",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 53,
    name: "building block-3",
    price: 350000,
    image: `${toy3}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Crispy toys",
    description: "Soft Building Blocks Toys",
    category: "building-blocks",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 54,
    name: "construction set-1",
    price: 180000,
    image: `${toy4}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "MeeFactory",
    description: "Pidoko Kids Wooden Blocks - 100 Pcs",
    category: "constructions",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 55,
    name: "construction set-2",
    price: 280000,
    image: `${toy5}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Gadget City",
    description: "Aged up Blocks",
    category: "constructions",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 56,
    name: "construction set-3",
    price: 250000,
    image: `${toy6}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Crispy toys",
    description: "Boxiki kids Wooden Stacking Montessori Toys",
    category: "constructions",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 57,
    name: "Car Toys-1",
    price: 180000,
    image: `${toy7}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Gadget City",
    description: "Remote Control Car for kids",
    category: "cars",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 58,
    name: "Car Toys-2",
    price: 180000,
    image: `${toy8}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Crispy toys",
    description: "Growsland Remote Control Car",
    category: "cars",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 59,
    name: "Car Toys-3",
    price: 120000,
    image: `${toy9}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Gadget City",
    description: "Die Cast Metal Toy Cars",
    category: "cars",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 60,
    name: "Soft Toys-1",
    price: 175000,
    image: `${toy10}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "MeeFactory",
    description: "Rabbit Stuffed Plush Animal Soft Toy",
    category: "soft-toys",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 61,
    name: "Soft Toys-2",
    price: 95000,
    image: `${toy11}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Crispy toys",
    description: "Panda Soft Toy",
    category: "soft-toys",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 62,
    name: "Soft Toys-3",
    price: 150000,
    image: `${toy12}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Gadget City",
    description: "Baby Soft Toy",
    category: "soft-toys",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 63,
    name: "Puzzle Toys-1",
    price: 145000,
    image: `${toy13}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "MeeFactory",
    description: "Wooden Animal Puzzles ",
    category: "puzzle-toys",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 64,
    name: "Puzzle Toys-2",
    price: 100000,
    image: `${toy14}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Crispy toys",
    description: "Wooden Toddler Puzzles",
    category: "puzzle-toys",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
  {
    id: 65,
    name: "Puzzle Toys-3",
    price: 120000,
    image: `${toy15}`,
    colors: ["#ff0000", "#00ff00", "#0000ff"],
    company: "Gadget City",
    description: "Animal Puzzles",
    category: "puzzle-toys",
    shipping: true,
    gen: "toy",
    stock: 17,
    reviews: 5,
    stars: 4.5,
  },
];
